# Getting started

## Download Anaconda

Anaconda Distribution (Python 3.XX):
- https://www.anaconda.com/distribution/ 
- https://www.datacamp.com/community/tutorials/installing-anaconda-windows (installation for windows)

</br> 
This should install Python and Jupyter Notebook.


To make sure, open terminal on Mac/Linux or Command Prompt on Windows and type "conda" 
</br> If you see an "unrecongnized command" prompt then you have installed it wrong and must add conda to your PATH variable 

Run a jupyter notebook:
- Open terminal on Mac/Linux or Command Prompt on Windows
- type: "jupyter notebook"

In [1]:
! python --version

Python 3.6.3 :: Anaconda custom (64-bit)


# Creating a virtual environment

in terminal/command prompt type: "conda create --name MMA-course"

Additional information about virtual environments: https://docs.conda.io/projects/conda/en/latest/user-guide/tasks/manage-environments.html

To go into virtual environment: "conda activate (name)"

in terminal/command prompt type: "pip install gym"

to logout of env do: "conda deactivate"

to see all of the virtual environment you have do: "conda env list"

## OpenAI Gym

http://gym.openai.com/envs/

</br>
http://gym.openai.com/docs/

### Basics of gym

In [1]:
import gym

In [12]:
env = gym.make('CartPole-v1') # create env

WARN: gym.spaces.Box autodetected dtype as <class 'numpy.float32'>. Please provide explicit dtype.


In [13]:
env.action_space # tells you the type of actions you can provide
                 # Discrete means integer values

Discrete(2)

In [14]:
env.observation_space # tells you the dimension of the state space
                      # Box means continuous values

Box(4,)

In [15]:
env.observation_space.high # tells you the the max values

array([4.8000002e+00, 3.4028235e+38, 4.1887903e-01, 3.4028235e+38],
      dtype=float32)

In [16]:
env.observation_space.low # tells you the min values

array([-4.8000002e+00, -3.4028235e+38, -4.1887903e-01, -3.4028235e+38],
      dtype=float32)

In [17]:
# Random action
env.action_space.sample()

1

### Full example 

In [19]:
env = gym.make('MountainCar-v0')
env.reset()
done = False
while not done:
    env.render()
    state, reward, done, _ = env.step(env.action_space.sample()) # take a random action
env.close()

AttributeError: 'NoneType' object has no attribute 'set_current'

### Breakdown of gym interface

Taking a step in the environment will return the next state, reward, whether the env is done or not as well as extra info.

In [10]:
env.reset()
next_state, reward, done, info = env.step(env.action_space.sample())

In [11]:
next_state

array([ 0.00819739,  0.20756179, -0.03395254, -0.2932077 ])

In [12]:
reward

1.0

In [13]:
done

False

In [14]:
env.close()